site_name: Miguel Amaral
repo_url: https://github.com/miguelzeph/miguelzeph.github.io
site_url: https://miguelzeph.github.io
theme:
  name: dracula # material
  palette:
    primary: 'teal'
    accent: 'orange'
  font:
    text: 'Lato'
    code: 'Fira Code'
  logo: 'about/img/profile.png'
  favicon: 'img/favicon.ico'

nav:
  - Home: index.md
  - "ğŸ‘¤ About Me": about/about.md
  - "ğŸ“š Skills": "skills/skills.md"
  - "ğŸ’¼ Projects":
      - "Project 1": projects/project_1.md
  - "ğŸ› ï¸ Services":
      - "Service 1": services/service_1.md
      - "Service 2": services/service_2.md
  - "ğŸ”¬ Scientific Articles": scientific_articles/scientific_articles.md
  - "ğŸ“ Contact": contact.md


plugins:
  - search
  # - awesome-pages
  # - markdownextradata

extra_css:
  - css/custom.css
  # Boostrap 4 (It was getting conflict with Dracula theme)
  # - https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css

extra_javascript:
  - js/custom.js
  # Google Analytics
  - https://www.googletagmanager.com/gtag/js?id=G-MV51GYN8DB
  - js/analytics.js
