site_name: |
  Miguel Angelo Do Amaral<br>
  <hr class="custom-hr">
  <span style="color: #8be9fd;">Data Engineer</span><br>
  <span style="color: #50fa7b;">&</span><br>
  <span style="color: #ffb86c;">Python Dev</span>
repo_url: https://github.com/miguelzeph/miguelzeph.github.io
site_url: https://miguelzeph.github.io
theme:
  name: dracula # material
  palette:
    primary: 'teal'
    accent: 'orange'
  font:
    text: 'Lato'
    code: 'Fira Code'
  logo: 'about/img/profile.png'
  favicon: 'img/favicon.ico'

nav:
  - "Home": index.md
  - "ğŸ‘¤ About Me": about/about.md
  - "ğŸ“š Skills": "skills/skills.md"
  - "ğŸ“‘ Documentation":
      - "ğŸ Python":
          - "01 - Python Good Starting": documentation/python/01_python_good_starting.md
          - "02 - Python Organize Code": documentation/python/02_python_organize_code.md
          - "03 - Typing & Docstring": documentation/python/03_typing_docstring.md
      - "ğŸ™ Version Control":
          - "01 - GitFlow": documentation/version_control/01_gitflow.md
  - "ğŸ’¼ Projects":
      - "Data Queue Keeper": projects/data_queue_keeper.md
      - "Train Your Classifier": projects/train_your_classifier.md
  - "ğŸ› ï¸ Services":
      - "Data Pipeline": services/data_pipeline.md
      - "Predictive Modeling": services/predictive_modeling.md
      - "Web App for Data Visualization": services/web_application_data_visualization.md
  - "ğŸ”¬ Scientific Articles": scientific_articles/scientific_articles.md
  - "ğŸ“ Contact": contact.md


plugins:
  - search
  # - awesome-pages
  # - markdownextradata

extra_css:
  - css/custom.css
  # Boostrap 4 (It was getting conflict with Dracula theme)
  # - https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css

extra_javascript:
  - js/custom.js
  # Google Analytics
  - https://www.googletagmanager.com/gtag/js?id=G-MV51GYN8DB
  - js/analytics.js
  # Hacking to add <meta> to the <head> tag.
  # - Google Search Console
  # Only way I found to add meta tags to the head
  # using the dracula theme.
  - js/inject_meta.js