site_name: |
  Miguel Angelo Do Amaral<br>
  <hr class="custom-hr">
  <span style="color: #8be9fd;">Data Engineer</span><br>
  <span style="color: #50fa7b;">&</span><br>
  <span style="color: #ffb86c;">Python Dev</span><br><br>
  <a href="https://amaralapps.com" target="_blank">ğŸš€<span style="color:rgb(250,100,100);">www.amaralApps.com</span>ğŸš€</a>
repo_url: https://github.com/miguelzeph/miguelzeph.github.io
site_url: https://miguelzeph.github.io
theme:
  name: dracula # material
  palette:
    primary: 'teal'
    accent: 'orange'
  font:
    text: 'Lato'
    code: 'Fira Code'
  logo: 'about/img/profile.png'
  favicon: 'img/favicon.ico'

nav:
  - "Home": index.md
  - "ğŸ‘¤ About Me": about/about.md
  - "ğŸ“š Skills": "skills/skills.md"
  - "ğŸ“‘ Documentation":
      - "ğŸ Python":
          - "01 - Python Good Starting": documentation/python/01_python_good_starting.md
          - "02 - Organazing into Modules": documentation/python/02_python_organize_modules.md
          - "03 - Configuration Management": documentation/python/03_configuration_management.md
          - "04 - Typing & Docstring": documentation/python/04_typing_docstring.md
          - "05 - Built-in functions": documentation/python/05_built-in_functions.md
          - "06 - Built-in methods": documentation/python/06_built-in_methods.md
      - "ğŸ™ Version Control":
          - "01 - GitFlow": documentation/version_control/01_gitflow.md
      - "ğŸ’¾ Data Basics":
          - "01 - Data Modeling": documentation/data/01_data_modeling.md
          - "02 - Data Structures": documentation/data/02_data_structures.md
          - "03 - Data Types": documentation/data/03_data_types.md
          - "04 - Data Structured": documentation/data/04_data_structured.md
          - "05 - Data Semi-Structured": documentation/data/05_data_semi_structured.md
          - "06 - Data Unstructured": documentation/data/06_data_unstructured.md
          - "07 - Data Blending": documentation/data/07_data_blending.md
      - "ğŸ‘· Data Engineering":
          - "01 - DE Introduction": documentation/data_engineering/01_introduction_data_engineering.md
      - "ğŸ’» AWS":
          - "01 - EC2 Instance - Deploying Docker": documentation/aws/01_deploy_docker_AWS_EC2.md
          - "02 - EC2 App - Custom Domain HTTP": documentation/aws/02_AWS_EC2_domain_http.md
          - "03 - EC2 App - Custom Domain HTTPS": documentation/aws/03_AWS_EC2_domain_https.md
          - "04 - EC2 App - (STREAMLIT) Custom Domain HTTPS": documentation/aws/04_AWS_EC2_domain_https_streamlit.md
      - "ğŸŒ API":
          - "01 - API base": documentation/api/01_api_basic.md
          - "02 - REST API vs GraphQL API": documentation/api/02_api_rest_graphql.md

  - "ğŸ’¼ Projects":
      - "AmaralApps Webpage": projects/amaralapps_webpage.md
      - "Minute News": projects/minute_news.md
      - "Data Queue Keeper": projects/data_queue_keeper.md
      - "Train Your Classifier": projects/train_your_classifier.md
      - "Airflow Guide": projects/airflow_guide.md
      - "Doc Lib": projects/document_library.md 
  - "ğŸ› ï¸ Services": services/services.md
  - "ğŸ”¬ Scientific Articles": scientific_articles/scientific_articles.md
  - "ğŸ“ Contact": contact.md


plugins:
  - search
  # - awesome-pages
  # - markdownextradata

extra_css:
  - css/custom.css
  # Boostrap 4 (It was getting conflict with Dracula theme)
  # - https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css

extra_javascript:
  - js/custom.js
  # Google Analytics
  - https://www.googletagmanager.com/gtag/js?id=G-MV51GYN8DB
  - js/analytics.js
  # Hacking to add <meta> to the <head> tag.
  # - Google Search Console
  # Only way I found to add meta tags to the head
  # using the dracula theme.
  - js/inject_search.js
  # Hacking tag head for Google Adsense
  - js/inject_adsense.js
